version: '2'
services:
        smart-doorbell:
                build: ./smart-doorbell
                privileged: true
                restart: always
                network_mode: "host"
                labels:
                        io.balena.features.kernel-modules: '1'